/* Reuses the entire existing form and final approval processing. */
window.ServiceContractApproval = (function () {
 'use strict'; let contract=null;
 async function load(client){const id=new URLSearchParams(location.search).get('service_contract');if(!id)return;
  const {data,error}=await client.rpc('erp_service_contract',{p_action:'get',p_id:id,p_payload:{}});
  if(error||!data||data.state!=='review'){showAlert('계약 최종본을 불러오지 못했습니다. 계약 관리에서 상태와 권한을 확인해 주세요.');return;}
  const category=document.getElementById('appCategory');if(!Array.from(category.options).some(o=>o.value==='일반품의')){showAlert('이 조합에서 일반품의를 사용하지 않습니다. 기존 결재 설정을 확인해 주세요.');return;}
  category.value='일반품의';handleCategoryChange();contract=data;
  switchTab('draft');const title=document.getElementById('proposalSubject');title.value=`${data.terms.client.name} 운영시스템 이용계약 체결`;title.dataset.autoGenerated='0';
  setApprovalEditorContent('<p>아래 계약 최종본의 체결에 대한 내부 결재를 요청드립니다.</p>');
  const box=document.createElement('div');box.id='serviceContractApprovalLink';box.className='alert alert-info mt-3';
  const text=document.createElement('p');text.textContent=`연결된 계약: ${data.terms.client.name} · 제${data.revision}판. 상신할 때 같은 최종 계약 본문·이용 조건을 자동 첨부합니다.`;
  const a=document.createElement('a');a.href='service_contracts.html?contract='+encodeURIComponent(data.id);a.target='_blank';a.rel='noopener';a.textContent='최종 계약서 확인';box.append(text,a);
  const details=document.createElement('details'),summary=document.createElement('summary'),body=document.createElement('pre');summary.textContent='연결된 계약 본문·이용 조건 확인';body.style.cssText='white-space:pre-wrap;font:inherit;max-height:480px;overflow:auto';body.textContent=data.approval_text;details.append(summary,body);box.append(details);(category.closest('.row')||category.parentElement).after(box);
 }
 function categoryChanged(type){if(contract&&type!=='일반품의'){contract=null;document.getElementById('serviceContractApprovalLink')?.remove();}}
 function snapshot(){return contract?{id:contract.id,revision:contract.revision,digest:contract.digest}:null;}
 return {load,categoryChanged,snapshot};
})();
