/* Version: 1.1.2 | 2026-10-06 */
'use strict';
(() => {
 const db=window.supabase.createClient('https://ifdqlwxgqgsvnawmhlfc.supabase.co','sb_publishable_lkVhLJDe8WmOPzsWOMkKdg_pjVwVS-h',{global:{headers:{'x-erp-host':window.CoopRouteGuard?.getErpRuntimeHost(location)||location.hostname}}});
 const $=id=>document.getElementById(id), names={acquisition:'자격취득 신고서',loss:'자격상실 신고서',separation:'이직확인서',unpaid_confirmation:'대표자 무보수 확인서'}, statuses={draft:'준비 중',submitted:'제출 확인',completed:'처리 완료'};
 const state={employees:[],cases:[],current:null,busy:false,baseline:'',pdfUrl:null};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date());
 const plus=(d,n)=>{const x=new Date(d+'T00:00:00Z');x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10);};
 const errorText=e=>({HR_ADMIN_REQUIRED:'인사 관리 권한이 필요합니다.',RESIGNATION_REQUIRED:'먼저 직원관리에서 퇴사 처리를 완료해 주세요. 미래 퇴사일의 서류는 해당 날짜가 지난 뒤 준비할 수 있습니다.',HIRE_DATE_REQUIRED:'직원관리에서 입사일을 입력해 주세요.',STALE_DOCUMENT:'다른 화면에서 문서가 변경되었습니다. 새로 불러온 뒤 다시 확인해 주세요.',DOCUMENT_LOCKED:'제출한 서류는 덮어쓸 수 없습니다.',DOCUMENT_NOT_FOUND:'이 조합에서 확인할 수 없는 문서입니다.',INVALID_DATE:'제출일과 처리 완료일을 달력에서 다시 확인해 주세요.',UNPAID_CONFIRMATION_REQUIRED:'대표자와 무보수 확인서 확인란을 선택해 주세요.',PDF_NOT_SUPPORTED:'무보수 확인서는 이 화면에서 제출 기록만 관리합니다.',TEST_EMPLOYEE_REQUIRED:'시험 출력은 이름이 ‘시험’으로 시작하는 합성 직원에게만 사용할 수 있습니다.'}[e?.message]||'처리하지 못했습니다. 입력값과 연결 상태를 확인해 주세요.');
 function message(t,bad=false){$('message').className='alert '+(bad?'alert-danger':'alert-info');$('message').textContent=t;}
 async function rpc(action,args={}){const {data,error}=await db.rpc('erp_hr_insurance',{p_action:action,...args});if(error)throw error;return data;}
 async function run(fn){if(state.busy)return;state.busy=true;const controls=Array.from(document.querySelectorAll('button,input,select,textarea')).map(b=>[b,b.disabled]);controls.forEach(([b])=>{b.disabled=true;});try{await fn();}catch(e){message(errorText(e),true);}finally{state.busy=false;controls.forEach(([b,disabled])=>{if(b.isConnected)b.disabled=disabled;});}}
 const field=(key,label,type='text',value='',max=80)=>`<div><label for="f_${key}">${esc(label)}</label><input id="f_${key}" data-field="${key}" class="form-control" type="${type}" value="${esc(value)}" ${type==='number'?'min="0" max="999999999999" step="1"':`maxlength="${max}"`}></div>`;
 const check=(key,label,value=false)=>`<label class="me-3"><input type="checkbox" data-field="${key}" ${value?'checked':''}> ${esc(label)}</label>`;
 function fields(spec,data){return `<div class="field-grid">${spec.map(([key,label,type,max])=>field(key,label,type||'text',data[key]??(type==='number'?0:''),max)).join('')}</div>`;}
 function defaults(payload){const c=payload.company,e=payload.employee,biz=String(c.bizNum??'').trim().replace(/[-\s]/g,'');return {management_no:/^\d{10}$/.test(biz)?biz+'0':'',company_name:c.orgName||c.company_name||'',company_address:c.address||c.company_address||'',company_phone:c.company_contact_phone||c.company_contact||'',employer:c.ceoName||c.chairman_name||'',monthly_income:Number(e.monthly_income||0),print_date:today(),hours_week:40,daily_hours:8,pension:false,health:false,employment:false,accident:false,representative:false,contract_fixed:false,pension_first_month:false,pension_last_month:false};}
 function formValues(payload){return {...defaults(payload),...payload.case.form_data};}
 function snapshot(){return JSON.stringify(Array.from($('workspace').querySelectorAll('input,select,textarea')).filter(f=>f.id!=='rrn'&&f.id!=='testOutput'&&f.id!=='confirmForm').map(f=>[f.id||f.dataset.field||f.dataset.cell,f.type==='checkbox'?f.checked:f.value]));}
 function canLeave(){return !state.current||snapshot()===state.baseline||confirm('저장하지 않은 내용을 버리고 이동할까요?');}
 async function list(){const r=await rpc('list');state.employees=r.employees;state.cases=r.cases;const prev=$('employee').value;$('employee').innerHTML=state.employees.map(e=>`<option value="${esc(e.emp_id)}">${esc(e.name)}${e.resign_date?' · 퇴사':''}</option>`).join('');if(prev)$('employee').value=prev;const qp=new URLSearchParams(location.search).get('employee');if(qp&&state.employees.some(e=>e.emp_id===qp))$('employee').value=qp;$('recipientNotice').textContent=r.recipient_count?'신고 기한 알림은 직원관리의 알림 담당자로 지정한 직원에게 전달됩니다.':'알림 담당자가 아직 없습니다. 직원관리 → 직원 상세 → 알림 담당자에서 ‘입사·퇴사 신고 알림’을 지정해 주세요. 준비할 업무는 아래에 계속 표시됩니다.';renderList();}
 function renderList(){const selected=$('employee').value;const cs=state.cases.filter(c=>c.emp_id===selected&&($('statusFilter').value==='all'||c.status==='draft'));$('taskList').innerHTML=cs.length?cs.map(c=>`<button class="task ${state.current?.case.id===c.id?'active':''}" data-case="${c.id}">${esc(names[c.kind])}<small>${esc(statuses[c.status])}${c.submitted_date?'<br>제출일 '+esc(c.submitted_date):c.kind==='unpaid_confirmation'?'':'<br>기준일 '+esc(c.event_date)}${c.completed_date?'<br>처리 완료일 '+esc(c.completed_date):''}${c.goal_date&&c.status==='draft'?'<br>처리 목표 '+esc(c.goal_date):''}</small></button>`).join(''):'<p class="hint">해당 이력이 없습니다.</p>';$('taskList').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(canLeave())void run(()=>open(b.dataset.case));});}
 async function open(id){const p=await rpc('get',{p_id:id});render(p);}
 function periodsTable(key,data){const wage=key==='wages';return `<div class="table-wrap"><table class="table"><thead><tr><th>시작일</th><th>종료일</th><th>${wage?'계산 일수':'보수지급 기초일수'}</th>${wage?'<th>기본급</th><th>기타 수당</th>':''}<th></th></tr></thead><tbody id="${key}Rows">${(data[key]||[]).map(row=>periodRow(key,row)).join('')}</tbody></table></div><button type="button" class="btn btn-sm btn-outline-secondary" data-add="${key}">기간 추가</button>`;}
 function periodRow(key,row={}){return `<tr>${['from','to','days',...(key==='wages'?['basic','other']:[])].map(cell=>`<td><input class="form-control form-control-sm" data-cell="${cell}" aria-label="${cell==='from'?'시작일':cell==='to'?'종료일':cell==='days'?'일수':cell==='basic'?'기본급':'기타 수당'}" type="${['from','to'].includes(cell)?'date':'number'}" min="0" step="1" value="${esc(row[cell]??(['from','to'].includes(cell)?'':0))}"></td>`).join('')}<td><button type="button" class="btn btn-sm btn-outline-danger" data-remove>삭제</button></td></tr>`;}
 function render(p){if(state.pdfUrl){URL.revokeObjectURL(state.pdfUrl);state.pdfUrl=null;}state.current=p;state.cases=state.cases.filter(item=>item.id!==p.case.id).concat(p.case);const c=p.case,e=p.employee,d=formValues(p);$('employee').value=e.emp_id;$('kind').value=c.kind;const locked=c.status!=='draft';
  let html=`<h2 class="mt-0">${esc(e.name)} · ${esc(names[c.kind])}</h2><p class="hint">${c.kind==='unpaid_confirmation'?'대표자 제출 기록':'입사일 '+esc(e.hire_date||'미입력')+(e.resign_date?' / 마지막 근무일 '+esc(e.resign_date):'')} · ${esc(statuses[c.status])}${c.submitted_date?' · 제출일 '+esc(c.submitted_date):''}${c.completed_date?' · 처리 완료일 '+esc(c.completed_date):''}</p>`;
  if(c.kind==='unpaid_confirmation'){
   html+='<h2>무보수 확인</h2>'+check('representative','대표자에 해당',d.representative)+check('unpaid_confirmation','대표자 무보수 확인서',d.unpaid_confirmation)+'<p class="hint mt-3">기관에 제출한 무보수 확인서의 제출 여부와 날짜를 기록합니다.</p>';
  }else{
  const event=c.kind==='acquisition'?e.hire_date:plus(e.resign_date,1);const next15=new Date(event+'T00:00:00Z');next15.setUTCMonth(next15.getUTCMonth()+1,15);const statutory=next15.toISOString().slice(0,10);
  html+=`<div class="alert alert-light border">${c.kind==='separation'?'퇴사 후 요청 없이 먼저 제출할 수 있습니다. 근로자 또는 고용센터의 요청을 받았다면 요청일로부터 10일 이내 발급·제출해야 합니다.':`건강보험 신고 기한: ${plus(event,14)} / 국민연금·고용보험 신고 기한: ${statutory}<br>내부 처리 목표: ${esc(c.goal_date)}. 적용 대상·예외와 산재보험 신고는 제출 기관에서 확인해 주세요.`}</div>`;
  if(c.kind==='separation')html+=field('request_date','발급 요청을 받은 날짜 (요청이 있을 때만)','date',c.request_date||'');
  html+='<h2>사업장 정보</h2><p class="hint">사업장관리번호는 사업자등록번호 뒤에 0을 붙여 미리 채웁니다. 기관에서 확인한 번호가 다르면 수정해 주세요.</p>'+fields([['management_no','4대보험 사업장관리번호 (11자리)'],['company_name','사업장 명칭'],['company_address','사업장 주소','text',200],['company_phone','사업장 전화번호'],['employer','신고인·대표자'],['print_date','신고서 작성일','date']],d);
  html+='<details><summary>사업장 추가 정보</summary>'+fields([['company_fax','팩스번호'],['postal','우편번호'],['unit_name','단위사업장 명칭'],['branch_name','영업소 명칭'],['agent_name','보험사무대행기관 명칭'],['agent_no','대행기관 번호'],['subcontract_no','하수급인 관리번호 (해당 시)']],d)+'</details>';
  if(c.kind!=='separation')html+='<h2>신고할 보험</h2><p class="hint">해당 직원의 가입 대상을 확인한 보험만 선택해 주세요. 적용 여부는 근무조건·나이 등에 따라 다릅니다.</p>'+['pension','health','employment','accident'].map((k,i)=>check(k,['국민연금','건강보험','고용보험','산재보험'][i],d[k])).join('');
  if(c.kind==='acquisition'){
   html+='<h2>자격취득 · '+esc(event)+'</h2>'+fields([['monthly_income','신고 월 소득·보수액 (원)','number'],['pension_code','국민연금 취득 부호'],['health_code','건강보험 취득 부호'],['occupation_code','고용보험 직종 부호 (2025 KECO)'],['hours_week','1주 소정 근로시간','number'],['contract_end','계약 종료 예정일 (계약직)','date']],d)+check('representative','대표자에 해당',d.representative)+check('pension_first_month','취득 월 연금 납부 희망',d.pension_first_month)+check('contract_fixed','계약직',d.contract_fixed);
   html+='<p class="hint mt-2">취득 부호와 직종 부호는 PDF에 포함된 공식 작성요령에서 확인할 수 있습니다. 보험별 취득일·신고 보수 또는 사업장관리번호가 다르면 보험을 나누어 별도 신고서를 준비해 주세요.</p><details><summary>외국인·감면 등 추가 기재</summary>'+fields([['nationality','국적 (외국인)'],['visa','체류 자격'],['pension_special','연금 특수직종 부호'],['pension_occupation','직역연금 부호'],['health_reduction','건강보험 감면 부호'],['public_account','공무원·교직원 회계명/부호'],['public_occupation','공무원·교직원 직종명/부호'],['charge_code','보험료 부과 부호'],['charge_reason','보험료 부과 사유']],d)+'</details>';
  }else{
   html+='<h2>퇴사 사유</h2>'+fields([['loss_code','고용보험 이직사유 코드'],['loss_reason','구체적 퇴사 사유 (10자 이상)','text',200]],d)+'<p class="hint mt-2">상실 신고와 이직확인서에는 실제 퇴사 사유를 동일하게 적어 주세요. 자진퇴사·계약만료 등은 공식 작성요령의 구분코드를 확인합니다.</p>';
   if(c.kind==='loss')html+='<h2>자격상실 · '+esc(event)+'</h2>'+fields([['pension_loss_code','국민연금 상실 부호'],['health_loss_code','건강보험 상실 부호'],['health_salary','건강보험 해당 연도 보수 총액','number'],['health_months','해당 연도 근무 개월수','number'],['previous_salary','건강보험 전년도 보수 (미정산 시)','number'],['previous_months','전년도 근무 개월수 (미정산 시)','number'],['employment_salary','고용보험 해당 연도 보수 총액','number'],['accident_salary','산재보험 해당 연도 보수 총액','number'],['previous_employment_salary','고용보험 전년도 보수 (미신고 시)','number'],['previous_accident_salary','산재보험 전년도 보수 (미신고 시)','number']],d)+check('pension_last_month','초일 취득·당월 상실 연금 납부 희망',d.pension_last_month);
   else{
    html+='<h2>피보험 단위기간</h2><p class="hint">최신 기간부터 입력해 주세요. 기초일수에는 보수가 지급된 날을 적습니다. 무급휴일·무급 결근을 제외하므로 달력 일수로 자동 확정하지 않습니다.</p>'+periodsTable('periods',d);
    html+='<h2>평균임금 산정명세</h2><p class="hint">이직일까지 직전 3개월에 해당하는 계산기간·기본급·수당을 입력하고 확인합니다. 근무 3개월 미만·휴직·상여금 정산 등은 공식 작성요령에 따라 조정합니다.</p>'+periodsTable('wages',d)+fields([['bonus','산정기간에 반영할 상여금 (공식 요령으로 안분한 금액)','number'],['leave_pay','산정기간에 반영할 연차수당 (안분 금액)','number'],['ordinary_daily','1일 통상임금 (근무 3개월 미만 필수)','number'],['base_daily','1일 기준보수 (해당 시)','number'],['daily_hours','1일 소정 근로시간 (1~8, 8은 8시간 이상)','number'],['short_days','초단시간 근로일수 (해당 시)','number']],d)+'<div id="totals" class="alert alert-light border mt-3"></div><details><summary>기준기간 연장 (해당 시)</summary>'+fields([['extend_code','연장 사유코드'],['extend_from','연장 시작일','date'],['extend_to','연장 종료일','date']],d)+'</details>';
   }
  }
  html+=`<details><summary>출력할 개인정보 확인</summary><p class="hint">이름·연락처·주소는 직원 정보에서 불러옵니다. 주민등록번호는 출력할 때만 권한을 확인해 가져오며 이 서류 초안에 평문으로 저장하지 않습니다. 등록 정보가 없다면 출력용으로만 입력해 주세요.</p><label for="rrn">출력용 주민등록번호</label><input class="form-control" id="rrn" autocomplete="off" inputmode="numeric" maxlength="14" placeholder="등록 정보가 없을 때만 입력"><label class="mt-3"><input id="testOutput" type="checkbox"> 합성 시험 직원 출력 (기관 제출 금지)</label></details>`;
  }
  html+=`<label class="mt-2"><input id="confirmForm" type="checkbox"> ${c.kind==='unpaid_confirmation'?'대표자와 제출할 서류를 확인했습니다.':'신고 대상·날짜·보수·사유를 확인했습니다.'}</label><div class="actions"><button id="save" class="btn btn-primary" ${locked?'disabled':''}>초안 저장</button>${c.kind==='unpaid_confirmation'?'':'<button id="pdf" class="btn btn-outline-primary">PDF 저장 · 인쇄</button>'}${c.status==='draft'?'<button id="submitted" class="btn btn-outline-success">기관 제출 확인</button>':c.status==='submitted'?'<button id="completed" class="btn btn-success">처리 완료 확인</button>':''}</div><div id="pdfPreview" class="mt-4"></div>`;
  $('workspace').innerHTML=html;if(locked)$('workspace').querySelectorAll('[data-field],[data-cell],[data-add],[data-remove]').forEach(f=>f.disabled=true);
  $('save').onclick=()=>void run(save);if($('pdf'))$('pdf').onclick=()=>void run(exportPdf);if($('submitted'))$('submitted').onclick=()=>setStatus('submitted');if($('completed'))$('completed').onclick=()=>setStatus('completed');
  $('workspace').querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const key=b.dataset.add;const rows=$(key+'Rows');if(rows.children.length>=(key==='periods'?12:4)){message('공식 서식에 들어가는 기간 수를 초과했습니다.',true);return;}rows.insertAdjacentHTML('beforeend',periodRow(key));bindRows();});bindRows();state.baseline=snapshot();renderList();message(locked?'제출 이력을 불러왔습니다.':c.kind==='unpaid_confirmation'?'대표자와 제출할 서류를 확인해 주세요.':'작성할 값을 확인하고 초안을 저장해 주세요.');
 }
 function bindRows(){$('workspace').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{b.closest('tr').remove();totals();});$('workspace').querySelectorAll('[data-cell],[data-field]').forEach(f=>f.oninput=totals);totals();}
 function read(){const form={};$('workspace').querySelectorAll('[data-field]').forEach(f=>{if(f.dataset.field==='request_date')return;form[f.dataset.field]=f.type==='checkbox'?f.checked:f.type==='number'?Number(f.value||0):f.value.trim();});for(const key of ['periods','wages']){if(!$(key+'Rows'))continue;form[key]=Array.from($(key+'Rows').children).map(tr=>Object.fromEntries(Array.from(tr.querySelectorAll('[data-cell]')).map(f=>[f.dataset.cell,f.type==='number'?Number(f.value||0):f.value])));}return form;}
 function totals(){if(!$('totals'))return;const d=read(),sum=(arr,k)=>arr.reduce((n,r)=>n+Number(r[k]||0),0);const days=sum(d.wages,'days'),money=sum(d.wages,'basic')+sum(d.wages,'other')+Number(d.bonus||0)+Number(d.leave_pay||0);$('totals').textContent=`보수지급 기초일수 합계 ${sum(d.periods,'days')}일 · 임금 계산기간 ${days}일 · 반영 임금 ${money.toLocaleString('ko-KR')}원${days?' · 계산상 1일 평균 '+Math.round(money/days).toLocaleString('ko-KR')+'원':''}`;}
 async function save(){const p=state.current;const r=await rpc('save',{p_id:p.case.id,p_revision:p.case.revision,p_data:{form:read(),request_date:$('f_request_date')?.value||null}});state.current=r;state.baseline=snapshot();await list();message('초안을 저장했습니다. PDF 출력 전에 신고 내용을 확인해 주세요.');}
 async function exportPdf(){if(!$('confirmForm').checked){message('신고 내용을 확인한 뒤 확인란을 선택해 주세요.',true);return;}const test=$('testOutput').checked,entered=$('rrn').value.replace(/\D/g,'');let p;try{if(state.current.case.status==='draft')await save();p=await rpc('pdf',{p_id:state.current.case.id,p_revision:state.current.case.revision,p_data:{test}});if(!p.rrn&&entered)p.rrn=entered;const bytes=await window.HrInsurancePdf.create(p);if(state.pdfUrl)URL.revokeObjectURL(state.pdfUrl);state.pdfUrl=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));$('pdfPreview').innerHTML='<h2>공식 서식 출력본</h2><p class="hint">PDF 인쇄 시 실제 크기(100%)로 인쇄하고 원본 방향을 유지해 주세요. 서명란은 서명하지 않은 상태로 남아 있습니다.</p><iframe id="preview" title="공식 신고서 PDF 미리보기"></iframe>';$('preview').src=state.pdfUrl;const a=document.createElement('a');a.href=state.pdfUrl;a.download=`${test?'시험용_':''}${names[p.case.kind]}_${p.employee.name}_${p.case.event_date}.pdf`;a.click();message('PDF를 만들었습니다. 기관 제출은 별도로 진행한 뒤 제출 확인을 기록해 주세요.');}catch(e){message(e.message||'PDF 생성에 실패했습니다.',true);}finally{if(p)p.rrn=null;$('rrn').value='';}}
 let statusTarget=null;
 function setStatus(status){if(state.busy||$('statusDialog').open)return;if(status==='submitted'&&!$('confirmForm').checked){message('신고 내용을 먼저 확인해 주세요.',true);return;}if(state.current.case.kind==='unpaid_confirmation'&&(!read().representative||!read().unpaid_confirmation)){message('대표자와 무보수 확인서 확인란을 선택해 주세요.',true);return;}statusTarget={status,id:state.current.case.id,revision:state.current.case.revision};$('statusTitle').textContent=status==='submitted'?'기관 제출 확인':'처리 완료 확인';$('statusDateLabel').textContent=status==='submitted'?'실제 제출일':'기관 처리 완료일';$('statusDate').value=today();$('statusDate').max=today();$('statusDate').min=status==='completed'?state.current.case.submitted_date||'':'';$('statusHelp').textContent=status==='submitted'?'제출일을 확인해 기록합니다. 기록 후에는 초안을 수정할 수 없습니다.':'기관에서 처리가 완료된 날짜를 확인해 기록합니다.';$('statusError').textContent='';renderCalendar(today().slice(0,7));$('statusCalendarPanel').classList.remove('hidden');$('statusDialog').showModal();$('statusDate').focus();}
 async function confirmStatus(){if(state.busy)return;const target=statusTarget,date=$('statusDate').value;if(!target||state.current?.case.id!==target.id||state.current.case.revision!==target.revision){$('statusError').textContent='문서가 변경되었습니다. 창을 닫고 다시 확인해 주세요.';return;}if(!validStatusDate(date,target.status,state.current.case.submitted_date)){ $('statusError').textContent='달력에서 올바른 날짜를 선택해 주세요. 미래 날짜나 제출일 이전의 처리 완료일은 기록할 수 없습니다.';return;}const button=$('statusConfirm');button.disabled=true;try{await run(async()=>{try{if(state.current.case.status==='draft')await save();const p=await rpc('status',{p_id:target.id,p_revision:state.current.case.revision,p_data:{status:target.status,date}});render(p);$('statusFilter').value='all';await list();$('statusDialog').close();statusTarget=null;message(target.status==='submitted'?'기관 제출을 기록했습니다.':'처리 완료를 기록했습니다.');}catch(e){if(state.current?.case.id===target.id)statusTarget={...target,revision:state.current.case.revision};$('statusError').textContent=errorText(e);throw e;}});}finally{button.disabled=false;}}
 function validStatusDate(date,status,submitted){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return false;const parsed=new Date(date+'T00:00:00Z');return !Number.isNaN(parsed.valueOf())&&parsed.toISOString().slice(0,10)===date&&date<=today()&&!(status==='completed'&&submitted&&date<submitted);}
 $('statusForm').onsubmit=e=>{e.preventDefault();void confirmStatus();};$('statusCancel').onclick=()=>{if(!state.busy)$('statusDialog').close();};$('statusDialog').addEventListener('cancel',e=>{if(state.busy)e.preventDefault();});$('statusDialog').addEventListener('close',()=>{statusTarget=null;});
 let calendarMonth='';
 function calendarDates(month){if(!/^\d{4}-\d{2}$/.test(month))return [];const first=new Date(month+'-01T00:00:00Z');if(Number.isNaN(first.valueOf())||first.toISOString().slice(0,7)!==month)return [];const end=new Date(first);end.setUTCMonth(end.getUTCMonth()+1);end.setUTCDate(0);return [...Array(first.getUTCDay()).fill(null),...Array.from({length:end.getUTCDate()},(_,i)=>month+'-'+String(i+1).padStart(2,'0'))];}
 function renderCalendar(month){const dates=calendarDates(month);if(!dates.length)return;calendarMonth=month;$('calendarMonth').textContent=Number(month.slice(0,4))+'년 '+Number(month.slice(5))+'월';const selected=$('statusDate').value,min=$('statusDate').min,max=$('statusDate').max;$('calendarGrid').innerHTML=dates.map(date=>date?`<button type="button" data-date="${date}" aria-label="${date}" aria-pressed="${date===selected}" ${date>max||(min&&date<min)?'disabled':''}>${Number(date.slice(8))}</button>`:'<span aria-hidden="true"></span>').join('');$('calendarGrid').querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{if(state.busy)return;$('statusDate').value=b.dataset.date;$('statusError').textContent='';renderCalendar(calendarMonth);});$('calendarNext').disabled=month>=today().slice(0,7);$('calendarPrev').disabled=Boolean(min&&month<=min.slice(0,7));}
 function moveCalendar(offset){if(state.busy)return;const month=new Date(calendarMonth+'-01T00:00:00Z');month.setUTCMonth(month.getUTCMonth()+offset);const next=month.toISOString().slice(0,7),min=$('statusDate').min;if(next>today().slice(0,7)||(min&&next<min.slice(0,7)))return;renderCalendar(next);}
 $('statusCalendar').onclick=()=>{$('statusCalendarPanel').classList.toggle('hidden');};$('calendarPrev').onclick=()=>moveCalendar(-1);$('calendarNext').onclick=()=>moveCalendar(1);$('statusDate').oninput=()=>{const month=$('statusDate').value.slice(0,7);if(calendarDates(month).length)renderCalendar(month);};
 window.addEventListener('beforeunload',e=>{if(state.current&&snapshot()!==state.baseline){e.preventDefault();e.returnValue='';}});
 $('prepare').onclick=()=>{if(canLeave())void run(async()=>render(await rpc('prepare',{p_emp_id:$('employee').value,p_kind:$('kind').value})));};
 $('employee').onchange=()=>{if(!canLeave()){$('employee').value=state.current.employee.emp_id;return;}state.current=null;state.baseline='';$('workspace').innerHTML='<p class="hint">서류 준비하기를 눌러 주세요.</p>';renderList();};$('statusFilter').onchange=renderList;
 void (async()=>{try{const gate=await window.ErpRuntimeGuard.requireUser(db,{alertFn:message,redirectUrl:'index.html'});if(!gate.ok)return;const runtime=await window.ErpRuntimeGuard.enforce(db,{moduleKey:'hr',moduleLabel:'직원관리',alertFn:message,redirectUrl:'index.html'});if(!runtime.ok)return;await list();const params=new URLSearchParams(location.search),employee=params.get('employee');if(employee&&state.employees.some(e=>e.emp_id===employee)){$('employee').value=employee;renderList();}$('app').classList.remove('hidden');message('직원과 서류를 선택해 주세요.');const id=params.get('document');if(id)await open(id);}catch(e){message(errorText(e),true);}})();
})();
