/* 1.5.0 · Signed-contract fees and immutable amendment agreements. */
(function () {
 'use strict';
 const $=id=>document.getElementById(id), BASE='https://ifdqlwxgqgsvnawmhlfc.supabase.co';
 const KEY='sb_publishable_lkVhLJDe8WmOPzsWOMkKdg_pjVwVS-h';
 const host=window.CoopRouteGuard?.getErpRuntimeHost(location)||location.hostname;
 const db=window.supabase.createClient(BASE,KEY,{global:{headers:{'x-erp-host':host}}});
 let context=null,current=null,busy=false,exporting=false,hasInk=false,draw=false,returnKey=null,returnKeyUntil=0,pinPromise=null,editBaseline='';
 let reviewerLinkRows=[],reviewerLinkContract=null,preferredReviewer=null;
 const stateNames={draft:'초안',review:'내부 결재·서명 준비',signed:'체결 완료',ended:'계약 종료'};
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=n=>Number(n||0).toLocaleString('ko-KR');
 const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const errors={SERVICE_ACCESS_DENIED:'이 조합의 계약을 확인할 권한이 없습니다.',SERVICE_ADMIN_REQUIRED:'지정 관리자만 처리할 수 있습니다.',SERVICE_REPRESENTATIVE_REQUIRED:'조합 기본정보에 등록된 이사장 본인 계정에서 서명해 주세요.',SERVICE_STALE_VERSION:'다른 화면에서 계약이 변경되었습니다. 새로 불러온 내용을 확인해 주세요.',SERVICE_DOCUMENT_LOCKED:'결재·서명이 시작된 계약서는 수정할 수 없습니다.',SERVICE_UNRESOLVED_TERMS:'개인정보 처리 위탁 명세의 미확정 항목을 먼저 확인·수정하고 확인란에 체크해 주세요.',SERVICE_APPROVALS_PENDING:'양측 조합의 내부 결재가 모두 완료된 뒤 서명할 수 있습니다.',SERVICE_APPROVAL_EXISTS:'이 조합의 내부 결재가 이미 연결되어 있습니다.',SERVICE_EXPORT_DENIED:'자료 다운로드 담당자와 이용기간을 확인해 주세요.',SERVICE_CONFIRM_ON_END_DATE:'종료 예정일 당일에 종료를 확정해 주세요.',SERVICE_ENDED_READ_ONLY:'종료된 조합은 자료 다운로드만 이용할 수 있습니다.',SERVICE_INVALID_DOWNLOAD_MANAGER:'해당 조합의 현직 관리자 중 자료를 받을 담당자를 선택해 주세요.',SERVICE_EXPORT_RATE_LIMIT:'다운로드 준비 요청이 많습니다. 잠시 뒤 다시 시도해 주세요.',SERVICE_FILE_CHANGED:'준비하는 동안 첨부가 변경되었습니다. 새 다운로드를 준비해 주세요.',SERVICE_INVALID_TERMS:'이용기간과 이용료를 확인해 주세요.',SERVICE_ENDING_LOCKED:'체결 완료된 계약만 종료를 요청할 수 있습니다.'};
 function message(value,kind='info'){ $('message').textContent=value;$('message').className='alert alert-'+kind; }
 Object.assign(errors,{INVALID_SECURE_PIN:'PIN이 일치하지 않습니다.',SECURE_PIN_NOT_CONFIGURED:'먼저 다운로드 PIN을 설정해 주세요.',SERVICE_RETURN_PIN_RATE_LIMIT:'PIN 확인이 여러 번 실패했습니다. 10분 뒤 다시 시도해 주세요.',SERVICE_RETURN_PIN_FORMAT:'PIN은 4자리 이상 입력해 주세요.',SERVICE_RETURN_SESSION_REQUIRED:'로그인 상태가 만료되었습니다. 같은 계정으로 다시 로그인해 주세요.',SERVICE_RETURN_DECRYPT_FAILED:'복호화하지 못한 자료가 있어 다운로드를 중단했습니다. 담당자에게 확인을 요청해 주세요.',SERVICE_RETURN_KEY_UNAVAILABLE:'자료 암호화 설정을 확인해야 합니다. 담당자에게 문의해 주세요.',SERVICE_EXPORT_TOO_LARGE:'자료가 한 번에 처리할 수 있는 크기를 넘었습니다. 담당자에게 분할 반환을 요청해 주세요.'});
 function errorText(e){const s=String(e?.message||'');return Object.entries(errors).find(([k])=>s.includes(k))?.[1]||'처리하지 못했습니다. 연결 상태와 입력 내용을 확인한 뒤 다시 시도해 주세요.';}
 async function rpc(action,payload={},id=current?.id){const {data,error}=await db.rpc('erp_service_contract',{p_action:action,p_id:id||null,p_payload:payload});if(error)throw error;return data;}
 async function task(fn){if(busy)return;busy=true;document.querySelectorAll('#detail button,#newForm button,#signForm button,#reviewForm button,#reviewerLinkForm button,#resolutionForm button,#draftHistoryDialog button').forEach(x=>x.disabled=true);try{await fn();}catch(e){message(errorText(e),'danger');}finally{busy=false;document.querySelectorAll('#detail button,#newForm button,#signForm button,#reviewForm button,#reviewerLinkForm button,#resolutionForm button,#draftHistoryDialog button').forEach(x=>x.disabled=false);updateReviewerLinkSelection();}}
 function oneYearEnd(start){if(!/^\d{4}-\d{2}-\d{2}$/.test(start||''))return '';const [y,m,d]=start.split('-').map(Number);if(y<1000||y>9998)return '';const date=new Date(Date.UTC(y,m-1,d));if(date.toISOString().slice(0,10)!==start)return '';const leap=m===2&&d===29;const next=new Date(Date.UTC(y+1,m-1,leap?28:d));if(!leap)next.setUTCDate(next.getUTCDate()-1);return next.toISOString().slice(0,10);}
 function draftSnapshot(){return $('editForm')?JSON.stringify({title:$('contractTitle').value.trim(),terms:readTerms(),body:$('contractBody').value}):'';}
 function unsaved(){return Boolean(editBaseline&&$('editForm')&&draftSnapshot()!==editBaseline);}
 function updateDraftStatus(){const el=$('draftStatus');if(el)el.textContent=unsaved()?'저장하지 않은 변경 내용이 있습니다.':'저장된 내용입니다.';}
 function allowDiscard(){return !unsaved()||confirm('저장하지 않은 변경 내용이 있습니다. 변경 내용을 버리고 계속할까요?');}
 function defaultTerms(parties){const s=today()<='2026-12-31'?'2027-01-01':today();return {...parties,start:s,end:oneYearEnd(s),annual_supply:300000,free_start:today()<='2026-12-31'?today():null,free_end:today()<='2026-12-31'?'2026-12-31':null,setup:'작업 범위·금액·부가가치세는 착수 전 별도로 서면 합의',special:'없음',privacy_finalized:false,village_enabled:false,village_annual_supply:0};}
 function defaultBody(){return window.ServiceContractTemplate.filter(x=>!x.text.startsWith('계약 체결일')&&!x.text.includes('양측은 본문 및 확정된')&&!/^(초기 설정 ·|기존 자료 이전 ·|그 밖의 합의 ·|제11조 별도 합의)/.test(x.text)).map(x=>x.text).join('\n\n');}
 async function reload(){const rows=await rpc('list',{},null);$('contractList').replaceChildren();if(!rows.length){$('contractList').textContent='등록된 계약이 없습니다.';return;}
  for(const r of rows){const b=document.createElement('button');b.type='button';b.className='service-contract-link';b.setAttribute('aria-current',String(current?.id===r.id));b.innerHTML=`<strong>${esc(r.client_name)}</strong><span class="service-state">${r.is_amendment?"변경합의서 · ":""}${esc(stateNames[r.state])}</span>${r.draft_review_pending?'<span class="service-review-badge">내 검토 대기</span>':''}<small class="d-block mt-2">${esc(r.start)} ~ ${esc(r.end)} · 제${Number(r.revision)}판</small>`;b.onclick=()=>task(()=>open(r.id));$('contractList').append(b);}}
 async function open(id,{discard=false}={}){if(!discard&&!allowDiscard())return false;const record=await rpc('get',{},id);current=record;render();await reload();return true;}
 function input(id,label,value,type='text',extra=''){return `<div><label for="${id}" class="form-label">${esc(label)}</label><input id="${id}" class="form-control" type="${type}" value="${esc(value)}" ${extra}></div>`;}
 const employeeContact=e=>[e.name,e.position].filter(Boolean).join(' ');
 function clientContactOptions(value){const contacts=[...new Set([value,...(current.reviewers||[]).map(employeeContact)].filter(Boolean))];return `<option value="">담당자를 선택해 주세요.</option>`+contacts.map(contact=>`<option value="${esc(contact)}"${contact===value?' selected':''}>${esc(contact)}</option>`).join('');}
 function refreshClientContacts(){const select=$('client_contact');if(select?.tagName==='SELECT')select.innerHTML=clientContactOptions(select.value);}
 function partyEditor(p,k,label){return `<fieldset class="service-section"><legend class="h5">${esc(label)} · ${esc(p.name)}</legend><p>대표자: ${esc(p.representative||'조합 기본정보에 등록해 주세요.')}</p><div class="service-field-grid">${['business_number','address','contact','phone','email'].map((f,i)=>k==='client'&&f==='contact'?`<div><label for="client_contact" class="form-label">담당자</label><select id="client_contact" class="form-select">${clientContactOptions(p.contact||'')}</select></div>`:input(k+'_'+f,['사업자등록번호','주소','담당자','전화번호','이메일'][i],p[f]||'',f==='email'?'email':'text','maxlength="300"')).join('')}</div></fieldset>`;}
 function editable(){return current.state==='draft'&&(context.platform||(context.admin&&context.coop_id===current.provider_coop_id));}
 function render(){const r=current,t=r.terms,e=r.ending?.contract_id?r.ending:null;const isProvider=context.platform||context.coop_id===r.provider_coop_id;const sameParty=context.coop_id===r.provider_coop_id||context.coop_id===r.client_coop_id;
  $('detail').innerHTML=`<div class="service-toolbar justify-content-between"><h2 class="h4 mb-0">${esc(r.title)}</h2><span class="service-state">${esc(stateNames[r.state])} · 제${r.revision}판</span></div><div class="service-toolbar mt-3"><button class="btn btn-outline-secondary" id="printContract">출력·PDF 저장</button><button class="btn btn-outline-secondary" id="reloadContract">새로 불러오기</button>${r.state==='signed'&&isProvider?'<button class="btn btn-outline-primary" id="createAmendment">변경합의서 만들기</button>':''}${r.amendment?'<button class="btn btn-outline-secondary" id="openOriginal">원계약 보기</button>':''}${r.state==='review'&&sameParty&&context.can_approve?'<button class="btn btn-outline-primary" id="startApproval">우리 조합 내부 결재 올리기</button>':''}${r.state==='review'&&sameParty&&context.representative?'<button class="btn btn-primary" id="startSign">대표자 서명·직인</button>':''}${r.state==='review'&&r.signatures&&Object.keys(r.signatures).length===0&&isProvider?'<button class="btn btn-outline-secondary" id="reopenContract">수정본 만들기</button>':''}</div>
   <div class="mt-3 service-help">${r.state==='draft'?'초안 검토 → 양측 내부 결재 → 대표자 서명·직인':'내부 결재 승인과 상대방의 계약 동의는 별도입니다. 양측 대표자의 서명이 있어야 체결 완료로 표시됩니다.'}</div>
   ${amendmentLinks(r)}${draftReviewHtml(r)}
   ${window.ServiceContractCollaboration?.html(r)||''}
   ${editable()?`<form id="editForm"><div class="service-section service-field-grid">${input('contractTitle','계약 제목',r.title,'text','required maxlength="200"')}${input('annualSupply','연간 이용료 · 부가세 별도',t.annual_supply,'number','required min="0" max="100000000" step="1"')}${input('periodStart','유료 서비스 개시일',t.start,'date','required')}${input('periodEnd','유료 이용 종료일',t.end,'date','required')}${input('freeStart','무료 제공 시작일 · 해당 없으면 비움',t.free_start,'date','max="2026-12-31"')}${input('setup','초기 설정비·범위',t.setup,'text','maxlength="1000"')}${input('special','별도 합의',t.special,'text','maxlength="2000"')}${r.amendment?input('changeEffective','변경 적용일',t.change_effective_on,'date',`required min="${t.start}" max="${t.end}"`):''}</div>${villageEditor(t)}${partyEditor(t.provider,'provider','제공자')} ${partyEditor(t.client,'client','이용자')}<section class="service-section"><label for="contractBody" class="form-label">계약 본문·개인정보 처리 위탁 별지</label><textarea id="contractBody" class="form-control service-body-editor" maxlength="180000" required>${esc(r.body)}</textarea><p id="draftStatus" class="service-help mt-2" role="status" aria-live="polite"></p><label class="form-check mt-3"><input id="privacyFinalized" class="form-check-input" type="checkbox" ${t.privacy_finalized?'checked':''}><span class="form-check-label">실제 사용하는 서비스의 처리 국가·항목·기간과 재위탁 범위를 확인하여 위탁 별지를 완성했습니다.</span></label><div class="service-toolbar mt-3"><button class="btn btn-primary" type="submit">초안 저장</button><button class="btn btn-outline-primary" id="freezeContract" type="button">결재용 최종본 확정</button></div></section></form>`:''}
   <section class="service-section"><h3 class="h5">양측 내부 결재</h3>${['provider','client'].map(k=>{const id=k==='provider'?r.provider_coop_id:r.client_coop_id;const d=r.approvals.find(a=>a.coop_id===id);return `<p><strong>${esc(t[k].name)}</strong>: ${d?esc(d.status)+' · '+esc(d.doc_no||'문서번호 확인 중'):'아직 결재를 올리지 않았습니다.'}${d&&context.coop_id===id?` <a href="approval.html?doc=${encodeURIComponent(d.id)}">결재 보기</a>`:''}</p>`;}).join('')}</section>
   <section class="service-section"><h3 class="h5">계약서 미리보기</h3><div class="service-contract-preview service-document" id="documentPreview">${documentHtml(r)}</div></section>${endingHtml(r,e,isProvider)}`;
  $('printContract').onclick=()=>{if(busy)return;if(unsaved()){message('저장하지 않은 변경 내용이 있습니다. ‘초안 저장’을 누른 뒤 출력해 주세요.','warning');return;}try{print(r);}catch{message('인쇄할 내용이 한 쪽을 넘습니다. 긴 당사자 정보를 줄이거나 본문을 문단으로 나누어 주세요.','warning');}};$('reloadContract').onclick=()=>task(()=>open(r.id));
  if($('createAmendment'))$('createAmendment').onclick=()=>task(async()=>{if(!confirm('기존 계약 조건을 불러와 변경합의서 초안을 만들까요? 원본 계약과 서명은 유지됩니다.'))return;const a=await rpc('amendment_create',{},r.id);await open(a.id);message('변경합의서 초안을 만들었습니다. 적용일과 변경 조건을 확인한 뒤 상대 검토·양측 결재·서명을 진행해 주세요.','success');});
  if($('openOriginal'))$('openOriginal').onclick=()=>task(()=>open(r.amendment.root_id));
  document.querySelectorAll('[data-amendment-id]').forEach(b=>b.onclick=()=>task(()=>open(b.dataset.amendmentId)));
  editBaseline=draftSnapshot();updateDraftStatus();
  bindDraftReview(r);bindReviewerLink(r);
  window.ServiceContractCollaboration?.bind(r,{rpc,task,open,message,errorText,allowDiscard,useProposal});
  if($('editForm')){if(r.amendment){$('periodStart').readOnly=true;$('periodEnd').readOnly=true;}$('villageEnabled').onchange=()=>{toggleVillage();updateDraftStatus();};toggleVillage();$('editForm').oninput=updateDraftStatus;$('editForm').onchange=updateDraftStatus;$('editForm').onsubmit=ev=>{ev.preventDefault();task(save);};$('periodStart').onchange=()=>{if(current.amendment)return;const end=oneYearEnd($('periodStart').value);if(end)$('periodEnd').value=end;updateDraftStatus();};$('freezeContract').onclick=()=>task(async()=>{if(!await save())return;if(!confirm('이 계약을 내부 결재용 최종본으로 확정할까요?'))return;current=await rpc('freeze',{revision:current.revision});await open(current.id);message('최종본을 확정했습니다. 각 조합의 기존 전자결재에서 내부 결재를 올려 주세요.','success');});}
  if($('reopenContract'))$('reopenContract').onclick=()=>task(async()=>{if(!confirm('이전 결재와 구분되는 수정본을 만들까요? 양측 내부 결재를 다시 받아야 합니다.'))return;await rpc('reopen',{revision:r.revision});await open(r.id);});
  if($('startApproval'))$('startApproval').onclick=()=>location.assign('approval.html?tab=draft&service_contract='+encodeURIComponent(r.id));
  if($('startSign'))$('startSign').onclick=()=>{$('signForm').reset();clearInk();$('signDialog').showModal();};
  if($('endRequestForm'))$('endRequestForm').onsubmit=ev=>{ev.preventDefault();task(async()=>{await rpc('end_request',{effective_on:$('endDate').value,reason:$('endReason').value});await open(r.id);message('종료 요청을 저장했습니다. 제공자 확인 전에는 서비스가 중지되지 않습니다.','success');});};
  if($('endConfirm'))$('endConfirm').onclick=()=>task(async()=>{if(!confirm('지정한 조합의 사용을 종료하고 자료 다운로드만 허용할까요? 실제 송금과 삭제는 실행하지 않습니다.'))return;const download_emp_ids=Array.from(document.querySelectorAll('input[name=returnManager]:checked')).map(x=>x.value);await rpc('end_confirm',{paid_supply:Number($('paidSupply').value),download_emp_ids});await open(r.id);message('계약 종료를 확인했습니다. 지정 담당자는 종료일부터 30일 동안 자료를 받을 수 있습니다.','success');});
  if($('refundConfirm'))$('refundConfirm').onclick=()=>task(async()=>{if(!confirm('실제로 환급을 마쳤는지 확인해 주세요. 이 버튼은 송금하지 않습니다.'))return;await rpc('refund_confirm',{refunded_on:$('refundDate').value});await open(r.id);});
  if($('cleanupNoteForm'))$('cleanupNoteForm').onsubmit=ev=>{ev.preventDefault();task(async()=>{await rpc('cleanup_note',{note:$('cleanupNote').value});await open(r.id);message('삭제·법정 보존 확인 기록을 저장했습니다. 자료를 삭제한 것은 아닙니다.','success');});};
 }
 function villageEditor(t){return '<section class="service-section"><label class="form-check"><input id="villageEnabled" type="checkbox" class="form-check-input" '+(t.village_enabled?'checked':'')+'><span class="form-check-label">햇빛소득마을 이용</span></label><div id="villageContractTerms" class="mt-3">'+input('villageContractFee','마을당 연간 이용료 · 부가세 별도',t.village_annual_supply||0,'number','min="0" max="100000000" step="1"')+'<p class="mt-2">마을 수에 따라 연간 청구하며, 중간에 추가한 마을은 생성일부터 남은 계약기간을 일할 계산합니다.</p></div></section>';}
 function toggleVillage(){if(!$('villageEnabled'))return;const active=$('villageEnabled').checked;$('villageContractTerms').hidden=!active;$('villageContractFee').required=active;}
 function villageTermsHtml(t){if(!t.village_enabled)return '';return '<h3>햇빛소득마을 이용 조건</h3><p>마을당 연간 이용료: 공급가액 '+money(t.village_annual_supply)+'원 · 부가세 별도\n운영 조합에 마을 수를 기준으로 연간 청구합니다. 중간에 추가한 마을은 생성일부터 계약 종료일까지의 남은 이용기간을 연간 일수로 나누어 일할 계산하여 청구합니다.</p>';}
 function amendmentLinks(r){if(!r.amendments?.length)return '';return '<section class="service-section"><h3 class="h5">연결된 변경합의서</h3>'+r.amendments.map(a=>'<button type="button" class="service-contract-link" data-amendment-id="'+esc(a.id)+'">'+esc(a.title)+' · '+esc(stateNames[a.state])+' · 적용일 '+esc(a.effective_on)+'</button>').join('')+'</section>';}
 function amendmentConditionsHtml(r){if(!r.amendment)return '';const before=r.amendment.before.terms,t=r.terms;const show=x=>'연간 이용료 '+money(x.annual_supply)+'원 · 햇빛소득마을 '+(x.village_enabled?'이용 / 마을당 연 '+money(x.village_annual_supply)+'원':'미포함');return '<h3>변경 전후 조건</h3><p>원계약: '+esc(r.amendment.root_title)+'\n변경 적용일: '+esc(t.change_effective_on)+'\n변경 전: '+esc(show(before))+'\n변경 후: '+esc(show(t))+'\n이 합의서에서 변경하지 않은 원계약 조건은 유지합니다.</p>';}
 Object.assign(errors,{SERVICE_INVALID_VILLAGE_TERMS:'햇빛소득마을 이용 여부와 마을당 요금을 확인해 주세요.',SERVICE_INVALID_AMENDMENT_PERIOD:'원계약 기간 안에서 변경 적용일을 선택해 주세요. 이용기간 연장은 새 계약으로 작성합니다.',SERVICE_AMENDMENT_ALREADY_OPEN:'작성 중인 변경합의서가 있습니다. 연결된 변경합의서를 확인해 주세요.',SERVICE_AMENDMENT_STALE_BASE:'최근 체결한 변경합의서에서 새 변경합의서를 만들어 주세요.',SERVICE_AMENDMENT_PERIOD_ENDED:'이용기간이 끝났습니다. 새 계약을 작성해 주세요.',SERVICE_AMENDMENT_USE_ORIGINAL:'계약 종료는 원계약에서 처리해 주세요.'});
 function readTerms(){const t=structuredClone(current.terms);for(const k of ['provider','client'])for(const f of ['business_number','address','contact','phone','email'])t[k][f]=$(k+'_'+f).value.trim();t.start=$('periodStart').value;t.end=$('periodEnd').value;t.annual_supply=Number($('annualSupply').value);t.free_start=$('freeStart').value||null;t.free_end=t.free_start?'2026-12-31':null;t.setup=$('setup').value;t.special=$('special').value;t.privacy_finalized=$('privacyFinalized').checked;t.village_enabled=$('villageEnabled').checked;t.village_annual_supply=t.village_enabled?Number($('villageContractFee').value):0;if(current.amendment)t.change_effective_on=$('changeEffective').value;return t;}
 function useProposal(s){if(!editable())return;const t=s.terms;for(const [id,value] of Object.entries({contractTitle:s.title,contractBody:s.body,annualSupply:t.annual_supply,periodStart:t.start,periodEnd:t.end,freeStart:t.free_start,setup:t.setup,special:t.special}))$(id).value=value??'';$('privacyFinalized').checked=Boolean(t.privacy_finalized);$('villageEnabled').checked=Boolean(t.village_enabled);$('villageContractFee').value=t.village_annual_supply||0;if($('changeEffective'))$('changeEffective').value=t.change_effective_on||'';toggleVillage();for(const k of ['provider','client'])for(const f of ['business_number','address','contact','phone','email'])$(k+'_'+f).value=t[k]?.[f]||'';updateDraftStatus();$('contractBody').focus();}
 async function save(){const form=$('editForm');if(!form?.reportValidity())return false;if(!unsaved())return true;const id=current.id,payload={revision:current.revision,title:$('contractTitle').value.trim(),terms:readTerms(),body:$('contractBody').value},controls=Array.from(form.querySelectorAll('input,textarea,select'));controls.forEach(x=>x.disabled=true);try{await rpc('save',payload,id);await open(id,{discard:true});message('초안을 저장했습니다.','success');return true;}finally{controls.forEach(x=>x.disabled=false);}}
 Object.assign(errors,{SERVICE_DRAFT_REVIEW_REQUIRED:'현재 초안을 상대 담당자가 검토 완료한 뒤 최종본을 확정할 수 있습니다.',SERVICE_INVALID_REVIEWER:'상대 조합에서 ERP 계정이 연결된 현직 담당자를 선택해 주세요.',SERVICE_REVIEW_RESPONSE_DENIED:'현재 검토 요청을 받은 담당자만 회신할 수 있습니다. 새로 불러와 요청 상태를 확인해 주세요.',SERVICE_INVALID_REVIEW_RESPONSE:'수정 요청 내용을 입력해 주세요.',SERVICE_REVIEW_ALREADY_PENDING:'이 담당자에게 같은 초안의 검토를 이미 요청했습니다.',SERVICE_INVALID_REVIEW_NOTE:'전달할 내용은 5,000자 이내로 입력해 주세요.'});
 const reviewNames={pending:'검토 대기',completed:'검토 완료',changes_requested:'수정 요청'};
 const reviewDate=s=>s?new Date(s).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'';
 function draftReviewHtml(r){const reviews=r.draft_reviews||[],latest=reviews.find(x=>!x.superseded);return `<section class="service-section service-review"><h3 class="h5">초안 검토</h3><p>${latest?`${esc(latest.reviewer_name)} · ${esc(reviewNames[latest.status]||'확인 필요')} · 제${Number(latest.revision)}판`:'아직 상대 담당자에게 검토를 요청하지 않았습니다.'}</p>${r.state==='draft'&&editable()?'<button type="button" class="btn btn-outline-primary" id="startDraftReview">상대 담당자에게 검토 요청</button>':''}${r.can_reply?`<form id="reviewResponseForm" class="mt-3"><label class="form-label" for="reviewResponseNote">검토 의견</label><textarea id="reviewResponseNote" class="form-control" rows="4" maxlength="10000" placeholder="수정 요청 시 내용을 적어 주세요."></textarea><div class="service-toolbar mt-3"><button type="submit" name="decision" value="completed" class="btn btn-primary">검토 완료</button><button type="submit" name="decision" value="changes_requested" class="btn btn-outline-primary">수정 요청</button></div></form>`:''}${reviews.length?`<details class="service-review-history mt-3" ${r.can_reply||latest?.status==='changes_requested'?'open':''}><summary>요청·회신 내역 (${reviews.length})</summary>${reviews.map(x=>`<article class="service-review-entry"><h4 class="h6">${esc(x.reviewer_name)} · ${esc(reviewNames[x.status]||'확인 필요')}${x.superseded?' · 이전 초안':''}</h4><p class="service-help">제${Number(x.revision)}판 · 요청 ${esc(reviewDate(x.requested_at))}${x.responded_at?' · 회신 '+esc(reviewDate(x.responded_at)):''}</p>${x.request_note?`<p><strong>전달 내용</strong><br>${esc(x.request_note)}</p>`:''}${x.response_note?`<p><strong>검토 의견</strong><br>${esc(x.response_note)}</p>`:''}</article>`).join('')}</details>`:''}</section>`;}
 function bindDraftReview(r){if($('startDraftReview'))$('startDraftReview').onclick=()=>task(async()=>{if(!await save())return;$('reviewForm').reset();$('reviewer').replaceChildren();const placeholder=document.createElement('option');placeholder.value='';placeholder.textContent='담당자를 선택해 주세요.';$('reviewer').append(placeholder);for(const e of current.reviewers||[]){const o=document.createElement('option');o.value=e.emp_id;o.textContent=e.name+(e.position?' · '+e.position:'');$('reviewer').append(o);}if(preferredReviewer?.contract===current.id)$('reviewer').value=preferredReviewer.emp_id;if(!current.reviewers?.length){if(canLinkReviewer(current)){await loadReviewerLink();return;}message('상대 조합에 ERP 계정이 연결된 담당자가 없습니다. 해당 조합 관리자에게 직원 계정 연결을 요청해 주세요.','warning');return;}$('reviewDialog').showModal();});
  if($('reviewResponseForm'))$('reviewResponseForm').onsubmit=ev=>{ev.preventDefault();const decision=ev.submitter?.value,note=$('reviewResponseNote').value.trim();if(decision==='changes_requested'&&!note){$('reviewResponseNote').setCustomValidity('수정 요청 내용을 입력해 주세요.');$('reviewResponseNote').reportValidity();return;}$('reviewResponseNote').setCustomValidity('');const review=r.draft_reviews.find(x=>!x.superseded);task(async()=>{await rpc('review_respond',{review_id:review.id,revision:r.revision,decision,note},r.id);await open(r.id);message(decision==='completed'?'초안 검토 완료를 회신했습니다.':'수정 요청을 회신했습니다.','success');});};
  if($('reviewResponseNote'))$('reviewResponseNote').oninput=()=>{$('reviewResponseNote').setCustomValidity('');};
 }
 Object.assign(errors,{SERVICE_LINK_SESSION_REQUIRED:'로그인 상태가 만료되었습니다. 다시 로그인한 뒤 연결해 주세요.',SERVICE_LINK_MANAGER_REQUIRED:'상대 조합의 전체 관리자 또는 통합관리자만 계정을 연결할 수 있습니다.',SERVICE_EMPLOYEE_ALREADY_CONNECTED:'이미 계정이 연결된 직원입니다. 목록을 다시 확인해 주세요.',SERVICE_VERIFIED_ACCOUNT_REQUIRED:'직원에 등록된 이메일로 로그인·인증을 먼저 완료해 주세요.',SERVICE_ACCOUNT_ALREADY_ASSIGNED:'이 로그인 계정은 해당 조합의 다른 직원에게 이미 연결되어 있습니다.',SERVICE_LINK_STALE:'직원 또는 로그인 계정 정보가 바뀌었습니다. 창을 닫고 목록을 다시 불러와 주세요.'});
 Object.assign(errors,{SERVICE_PROPOSAL_PENDING:'확인 대기 중인 수정안을 먼저 반영하거나 미반영 처리해 주세요.',SERVICE_PROPOSAL_DENIED:'현재 초안 검토를 요청받은 상대 담당자만 수정안을 보낼 수 있습니다.',SERVICE_STALE_PROPOSAL:'수정안이나 담당자가 변경되었습니다. 새로 불러온 내용을 확인해 주세요.',SERVICE_PROPOSAL_UNCHANGED:'현재 저장본과 달라진 내용이 없습니다.',SERVICE_HISTORY_NOT_FOUND:'해당 저장본을 찾지 못했습니다. 목록을 다시 불러와 주세요.',SERVICE_HISTORY_CONFLICT:'저장본 확인이 필요해 처리를 중단했습니다. 담당자에게 문의해 주세요.'});
 function canLinkReviewer(r){return r?.state==='draft'&&!context.closed&&(context.platform||(context.admin&&context.coop_id===r.client_coop_id));}
 async function reviewerLinkRpc(action,id,employee=null){const {data,error}=await db.rpc('erp_service_contract_reviewer_link',{p_action:action,p_contract:id,p_emp_id:employee?.emp_id||null,p_expected:employee?.expected||null});if(error)throw error;return data;}
 function updateReviewerLinkStatus(rows=current.reviewers||[]){const status=$('reviewerLinkStatus');if(!status)return;const names=[...new Set(rows.map(e=>e.name).filter(Boolean))];status.textContent=names.length?'연결됨 - '+names.join(', '):'';status.hidden=!names.length;}
 function bindReviewerLink(r){if(!canLinkReviewer(r))return;const section=$('detail').querySelector('.service-review'),toolbar=document.createElement('div'),button=document.createElement('button'),status=document.createElement('span');toolbar.className='service-toolbar';if($('startDraftReview'))toolbar.append($('startDraftReview'));button.type='button';button.className='btn btn-outline-secondary';button.id='startReviewerLink';button.textContent='상대 담당자 계정 연결';button.onclick=()=>task(loadReviewerLink);status.id='reviewerLinkStatus';status.className='text-success';status.setAttribute('role','status');toolbar.append(button,status);section.querySelector('p').after(toolbar);updateReviewerLinkStatus();if(!editable()){void reviewerLinkRpc('list',r.id).then(result=>{if(current?.id===r.id&&$('reviewerLinkStatus')===status)updateReviewerLinkStatus((result.employees||[]).filter(e=>e.connected));}).catch(()=>{if(current?.id===r.id&&$('reviewerLinkStatus')===status){status.textContent='연결 상태를 확인하지 못했습니다.';status.hidden=false;status.className='text-danger';}});}}
 function updateReviewerLinkSelection(){const select=$('reviewerLinkEmployee'),button=$('confirmReviewerLink');if(!select||!button)return;const employee=reviewerLinkRows.find(x=>x.emp_id===select.value);button.disabled=busy||!employee?.linkable;const info=$('reviewerLinkInfo');if(!employee){info.textContent=reviewerLinkRows.length?'연결할 직원을 선택해 주세요.':'등록된 현직 직원이 없습니다.';return;}info.textContent=(employee.email?employee.email+' · ':'')+(employee.connected?'이미 로그인 계정이 연결되어 있습니다.':employee.linkable?'등록된 이메일로 인증한 계정을 연결합니다. 이 직원의 기존 업무 권한으로 ERP를 이용하게 됩니다.':'연결 가능한 인증 계정이 없습니다. 등록된 이메일로 로그인·인증을 먼저 완료해 주세요.');}
 function populateReviewerLink(){const select=$('reviewerLinkEmployee');select.replaceChildren();const blank=document.createElement('option');blank.value='';blank.textContent=reviewerLinkRows.length?'직원을 선택해 주세요.':'등록된 현직 직원이 없습니다.';select.append(blank);for(const e of reviewerLinkRows){const o=document.createElement('option');o.value=e.emp_id;o.textContent=e.name+(e.position?' · '+e.position:'')+(e.connected?' · 연결됨':e.linkable?' · 연결 가능':' · 인증 필요');select.append(o);}updateReviewerLinkSelection();}
 async function loadReviewerLink(){const id=current.id,result=await reviewerLinkRpc('list',id);reviewerLinkContract=id;reviewerLinkRows=result.employees||[];$('reviewerLinkForm').reset();$('reviewerLinkError').textContent='';$('reviewerLinkOrg').textContent=result.client_name||current.terms.client.name;populateReviewerLink();$('reviewerLinkDialog').showModal();}
 function clearReviewerLink(){reviewerLinkRows=[];reviewerLinkContract=null;updateReviewerLinkSelection();}
 async function connectReviewerLink(){const id=reviewerLinkContract,employee=reviewerLinkRows.find(x=>x.emp_id===$('reviewerLinkEmployee').value);if(!id||!employee?.linkable)return;$('reviewerLinkError').textContent='';try{const result=await reviewerLinkRpc('link',id,employee);preferredReviewer={contract:id,emp_id:result.emp_id};$('reviewerLinkDialog').close();clearReviewerLink();message(result.name+' 님의 로그인 계정을 연결했습니다. 초안 검토 요청은 별도로 보내 주세요.','success');if(current?.id===id){try{const fresh=await rpc('get',{},id);if(unsaved()){current.reviewers=fresh.reviewers;refreshClientContacts();updateReviewerLinkStatus();}else{current=fresh;render();await reload();}}catch{message('계정 연결은 완료했습니다. 담당자 목록은 ‘새로 불러오기’로 확인해 주세요.','warning');}}}catch(e){$('reviewerLinkError').textContent=errorText(e);}}
 function partyHtml(p,heading,s){return `<div class="service-party"><h3>${esc(heading)}</h3><strong>${esc(p.name)}</strong><p>대표자: 이사장 ${esc(p.representative)}\n사업자등록번호: ${esc(p.business_number)}\n주소: ${esc(p.address)}\n담당자: ${esc(p.contact)}\n전화: ${esc(p.phone)}\n이메일: ${esc(p.email)}</p>${s?`<div class="service-signature"><p>서명: 이사장 ${esc(s.name)}<br>${esc(new Date(s.signed_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}))}</p><img src="${esc(s.signature)}" alt="대표자 서명"><img src="${esc(s.seal)}" alt="조합 직인"></div>`:''}</div>`;}
 function documentHtml(r){const t=r.terms;return `<h1 class="h3">${esc(r.title)}</h1><p>${esc(t.provider.name)}과 ${esc(t.client.name)}은 홈페이지와 협동조합 운영시스템의 제공 및 이용에 관하여 다음과 같이 계약합니다.</p><h3>제1조 계약 당사자</h3><div class="service-parties">${partyHtml(t.provider,'제공자')}${partyHtml(t.client,'이용자')}</div><h3>제2조 이용 조건</h3><p>유료 이용기간: ${esc(t.start)} ~ ${esc(t.end)}\n유료 서비스 개시일: ${esc(t.start)}\n연간 이용료: 공급가액 ${money(t.annual_supply)}원 + 부가가치세 ${money(Math.floor(t.annual_supply/10))}원 = 합계 ${money(Number(t.annual_supply)+Math.floor(t.annual_supply/10))}원\n초기 설정: ${esc(t.setup)}\n납부 방법: 제공자가 청구서로 지정한 계좌로 입금${t.free_start?'\n무료 제공기간: '+esc(t.free_start)+' ~ 2026-12-31':''}</p>${villageTermsHtml(t)}${amendmentConditionsHtml(r)}${r.body.split(/\n\s*\n/).map(p=>/^제\d+조|^별지 |^\d+ [^.]|^(Supabase|Cloudflare|GitHub) ·/.test(p)?`<h3>${esc(p)}</h3>`:`<p>${esc(p)}</p>`).join('')}<h3>별도 합의</h3><p>${esc(t.special||'없음')}</p><h3>전자서명·직인</h3><p>양측은 본문과 개인정보 처리 위탁 별지의 같은 최종본을 확인하여 계약을 체결합니다.</p><div class="service-parties">${partyHtml(t.provider,'제공자',r.signatures?.provider)}${partyHtml(t.client,'이용자',r.signatures?.client)}</div><p>계약 상태: ${esc(stateNames[r.state])} · 제${r.revision}판</p>`;}
 function endingHtml(r,e,isProvider){if(r.amendment)return '';if(r.state!=='signed'&&!e)return '';return `<section class="service-section"><h3 class="h5">계약 종료 처리</h3>${!e?.confirmed_at&&(context.platform||(context.coop_id===r.client_coop_id&&context.admin))?`<form id="endRequestForm"><div class="service-field-grid">${input('endDate','종료 희망일',e?.effective_on||today(),'date',`required min="${today()}"`)}${input('endReason','종료 사유',e?.reason||'','text','required maxlength="2000"')}</div><button type="submit" class="btn btn-outline-secondary mt-3">종료 요청 저장</button></form>` : !e?.confirmed_at?`<p>종료 요청은 이용 조합 관리자 또는 통합관리자가 등록합니다.</p>${e?`<p>요청한 종료일: ${esc(e.effective_on)} · ${esc(e.reason)}</p>`:''}`:`<p>종료일: ${esc(e.effective_on)} · 자료 다운로드 종료일: ${esc(e.download_until)}</p><p class="fw-bold">환급할 공급가액 ${money(e.refund_supply)}원 + 부가세 ${money(e.refund_vat)}원</p><p>${e.refunded_on?'환급 확인일: '+esc(e.refunded_on):'아직 실제 환급을 확인하지 않았습니다.'}</p>`}
 ${e&&!e.confirmed_at&&context.platform?`<div class="mt-4"><h4 class="h6">종료 확정 전 확인</h4>${input('paidSupply','실제 납부한 연간 공급가액',r.terms.annual_supply,'number','min="0" step="1"')}<p class="mt-3">종료 후 자료를 받을 해당 조합의 관리자</p><div class="service-checkboxes">${r.managers.map(m=>`<label><input type="checkbox" name="returnManager" value="${esc(m.emp_id)}"> ${esc(m.name)} ${esc(m.position)}</label>`).join('')||'연결된 관리자 계정을 먼저 등록해 주세요.'}</div><button id="endConfirm" class="btn btn-outline-danger mt-3" type="button">종료일에 사용 종료 확인</button></div>`:''}
 ${e?.confirmed_at&&context.platform?`<div class="service-field-grid mt-3">${!e.refunded_on?input('refundDate','실제 환급일',today(),'date',`max="${today()}"`):''}${!e.refunded_on?'<div class="align-self-end"><button id="refundConfirm" type="button" class="btn btn-outline-primary">실제 환급 확인</button></div>':''}</div><form id="cleanupNoteForm" class="mt-4"><label for="cleanupNote" class="form-label">삭제 일정·결과와 법정 보존 예외</label><textarea id="cleanupNote" class="form-control" rows="4" maxlength="10000">${esc(e.cleanup_note)}</textarea><p class="service-help mt-2">온라인 자료는 반환 접근기간 뒤 5영업일 이내, 복구 사본은 종료 후 90일 이내에 확인해야 합니다. 공용 백업은 여기서 삭제하지 않습니다.</p><button class="btn btn-outline-secondary" type="submit">확인 기록 저장</button></form>`:''}</section>`;}
 function clearInk(){const cv=$('signCanvas');cv.getContext('2d').clearRect(0,0,cv.width,cv.height);hasInk=false;}
 function ink(){const cv=$('signCanvas'),ctx=cv.getContext('2d');ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#111';function pos(e){const r=cv.getBoundingClientRect();return [(e.clientX-r.left)*cv.width/r.width,(e.clientY-r.top)*cv.height/r.height];}cv.onpointerdown=e=>{draw=true;cv.setPointerCapture(e.pointerId);ctx.beginPath();ctx.moveTo(...pos(e));};cv.onpointermove=e=>{if(!draw)return;ctx.lineTo(...pos(e));ctx.stroke();hasInk=true;};cv.onpointerup=cv.onpointercancel=()=>draw=false;}
 async function sealPng(file){if(!file||file.size>5*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('SERVICE_IMAGE_REQUIRED');const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>40000000){bitmap.close();throw Error('SERVICE_IMAGE_REQUIRED');}const cv=document.createElement('canvas');const scale=Math.min(1,500/Math.max(bitmap.width,bitmap.height));cv.width=Math.max(1,Math.round(bitmap.width*scale));cv.height=Math.max(1,Math.round(bitmap.height*scale));cv.getContext('2d').drawImage(bitmap,0,0,cv.width,cv.height);bitmap.close();return cv.toDataURL('image/png');}
 function print(r){const root=$('printRoot');root.innerHTML='';root.style.display='block';root.style.position='absolute';root.style.left='-10000px';const source=document.createElement('div');source.innerHTML=documentHtml(r);let page,content;
  const addPage=()=>{page=document.createElement('section');page.className='service-paper';content=document.createElement('div');content.className='service-paper-content';page.append(content);root.append(page);};addPage();
  for(const node of Array.from(source.children)){content.append(node);if(content.scrollHeight<=content.clientHeight)continue;node.remove();let heading=null;if(/^H[1-4]$/.test(content.lastElementChild?.tagName||'')){heading=content.lastElementChild;heading.remove();}if(content.children.length)addPage();if(heading)content.append(heading);content.append(node);
   if(content.scrollHeight>content.clientHeight&&node.tagName==='P'){node.remove();let text=node.textContent;while(text){let lo=1,hi=text.length,fit=0;const p=document.createElement('p');content.append(p);while(lo<=hi){const mid=Math.floor((lo+hi)/2);p.textContent=text.slice(0,mid);if(content.scrollHeight<=content.clientHeight){fit=mid;lo=mid+1;}else hi=mid-1;}if(!fit){p.remove();addPage();continue;}let cut=text.lastIndexOf(' ',fit);if(cut>fit*.7)fit=cut+1;p.textContent=text.slice(0,fit);text=text.slice(fit);if(text)addPage();}}
   else if(content.scrollHeight>content.clientHeight){root.replaceChildren();root.removeAttribute('style');throw Error('PRINT_OVERFLOW');}
  }
  const pages=Array.from(root.children);pages.forEach((p,i)=>{const footer=document.createElement('footer');footer.textContent=`제${r.revision}판 · ${i+1} / ${pages.length}`;p.append(footer);});root.removeAttribute('style');const old=document.title;document.title=`운영시스템_${r.amendment?"변경합의서":"이용계약서"}_${r.terms.client.name}`;window.print();document.title=old;
 }
 // Bounded ZIP groups, compressed when supported. Attachments are never executed.
 const crcTable=Uint32Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0;});
 function crc(bytes){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
 async function zip(entries){
  const enc=new TextEncoder(),parts=[],central=[],now=new Date();let off=0;
  const dosTime=(now.getHours()<<11)|(now.getMinutes()<<5)|Math.floor(now.getSeconds()/2),dosDate=((now.getFullYear()-1980)<<9)|((now.getMonth()+1)<<5)|now.getDate();
  for(const [name,blob] of entries){
   const n=enc.encode(name),bytes=new Uint8Array(await blob.arrayBuffer()),c=crc(bytes);let packed=bytes,method=0;
   if(typeof CompressionStream==='function'&&bytes.length<10*1024*1024){
    try{const compressed=new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(new CompressionStream('deflate-raw'))).arrayBuffer());if(compressed.length<bytes.length){packed=compressed;method=8;}}catch{/* STORE is a valid ZIP fallback. */}
   }
   const h=new Uint8Array(30+n.length),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint16(8,method,true);v.setUint16(10,dosTime,true);v.setUint16(12,dosDate,true);v.setUint32(14,c,true);v.setUint32(18,packed.length,true);v.setUint32(22,bytes.length,true);v.setUint16(26,n.length,true);h.set(n,30);parts.push(h,packed);
   const x=new Uint8Array(46+n.length),w=new DataView(x.buffer);w.setUint32(0,0x02014b50,true);w.setUint16(4,20,true);w.setUint16(6,20,true);w.setUint16(8,0x800,true);w.setUint16(10,method,true);w.setUint16(12,dosTime,true);w.setUint16(14,dosDate,true);w.setUint32(16,c,true);w.setUint32(20,packed.length,true);w.setUint32(24,bytes.length,true);w.setUint16(28,n.length,true);w.setUint32(42,off,true);x.set(n,46);central.push(x);off+=h.length+packed.length;
  }
  const clen=central.reduce((s,p)=>s+p.length,0),end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,entries.length,true);v.setUint16(10,entries.length,true);v.setUint32(12,clen,true);v.setUint32(16,off,true);return new Blob([...parts,...central,end],{type:'application/zip'});
 }
 const safeName=s=>String(s||'자료').replace(/[\\/:*?"<>|\x00-\x1f]/g,'_').slice(0,150);
 function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=safeName(name);a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
 async function ensureGrant(){
  if(returnKey&&Date.now()<returnKeyUntil)return returnKey;
  if(pinPromise)return pinPromise;
  const {data:state,error}=await db.rpc('erp_service_return_unlock',{});if(error)throw error;
  $('returnPinForm').reset();$('returnPinError').textContent='';$('initialPinFields').hidden=state.configured;$('returnPinConfirm').required=!state.configured;$('returnPinLabel').textContent=state.configured?'보안 다운로드 PIN':'처음 사용할 다운로드 PIN';
  pinPromise=new Promise((resolve,reject)=>{
   const dialog=$('returnPinDialog'),button=$('confirmReturnPin');let pending=false;
   const finish=(key)=>{dialog.close();$('returnPinForm').reset();dialog.oncancel=null;$('cancelReturnPin').onclick=null;pinPromise=null;key?resolve(key):reject(Error('RETURN_CANCELLED'));};
   $('cancelReturnPin').onclick=()=>{if(!pending)finish(null);};dialog.oncancel=e=>{e.preventDefault();if(!pending)finish(null);};
   $('returnPinForm').onsubmit=async e=>{e.preventDefault();if(pending)return;
    if(!state.configured&&$('returnPin').value!==$('returnPinConfirm').value){$('returnPinError').textContent='두 PIN이 일치하지 않습니다.';return;}
    pending=true;button.disabled=true;$('cancelReturnPin').disabled=true;
    try{const {data,error:err}=await db.rpc('erp_service_return_unlock',{p_pin:$('returnPin').value,p_set_initial:!state.configured});if(err)throw err;if(!data?.ok)throw Error(data?.error||'INVALID_SECURE_PIN');
     returnKey=data.access_key;returnKeyUntil=Date.now()+(data.expires_in-60)*1000;finish(returnKey);
    }catch(err){$('returnPinError').textContent=errorText(err);$('returnPin').value='';$('returnPinConfirm').value='';}
    finally{pending=false;button.disabled=false;$('cancelReturnPin').disabled=false;}
   };
   dialog.showModal();$('returnPin').focus();
  });
  return pinPromise;
 }
 async function returnRequest(path,payload,key){
  const {data:s}=await db.auth.getSession();if(!s.session)throw Error('SERVICE_RETURN_SESSION_REQUIRED');
  return fetch(BASE+path,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+s.session.access_token,'Content-Type':'application/json','x-erp-host':host,'x-service-return-key':key},body:JSON.stringify(payload),cache:'no-store'});
 }
 async function returnRpc(args){const res=await returnRequest('/rest/v1/rpc/erp_service_export',args,await ensureGrant());const data=await res.json();if(!res.ok){if(res.status===403){returnKey=null;returnKeyUntil=0;}throw Error(data?.message||'SERVICE_EXPORT_DENIED');}return data;}
 async function fileBlob(job,f){
  const res=await returnRequest('/functions/v1/service-data-return',{export_id:job.id,object_id:f.id},await ensureGrant());
  if(!res.ok){if(res.status===403){returnKey=null;returnKeyUntil=0;}throw Error('SERVICE_FILE_CHANGED');}
  const blob=await res.blob();if(blob.size!==Number(f.size))throw Error('SERVICE_FILE_CHANGED');return blob;
 }
 function attachmentGroups(files){
  const result=[];let batch=[],bytes=0;
  files.forEach((file,index)=>{const size=Number(file.size)||0;if(batch.length&&(batch.length>=200||bytes+size>50*1024*1024)){result.push(batch);batch=[];bytes=0;}batch.push({file,index});bytes+=size;});
  if(batch.length)result.push(batch);return result;
 }
 async function exportData(){
  if(exporting)return;exporting=true;$('exportData').disabled=true;const progress=$('exportProgress');progress.hidden=false;progress.textContent='PIN 확인 후 반환 자료를 준비합니다.';
  try{
   await ensureGrant();const job=await returnRpc({p_action:'start'}),grouped=new Map();
   for(let p=1;p<=job.pages;p++){progress.textContent='업무자료 '+p+' / '+job.pages+' 묶음을 확인하는 중입니다.';const data=await returnRpc({p_action:'page',p_export_id:job.id,p_page:p});if(!data?.rows)throw Error('EXPORT_PAGE_MISSING');if(!grouped.has(data.label))grouped.set(data.label,[]);grouped.get(data.label).push(...data.rows);}
   const groups=attachmentGroups(job.files),manifest={created_on:today(),coop:job.coop_name,datasets:job.manifest,notes:job.notes,attachment_archives:groups.length,files:job.files.map((f,i)=>({name:f.name,size:f.size,owner:f.owner_name||job.coop_name,ownership:f.ownership_source||'조합 경로',download_name:'첨부/'+String(i+1).padStart(4,'0')+'_'+safeName(f.name)}))};
   const entries=[['반환_내역.json',new Blob([JSON.stringify(manifest,null,2)],{type:'application/json'})],['안내.txt',new Blob([job.notes.join('\n')+'\n첨부 원본은 별도 첨부 ZIP을 모두 내려받아야 합니다. 반환 내역의 파일 목록과 실제 저장한 파일을 대조해 주세요.'])]];
   for(const [label,rows] of grouped){entries.push(['업무자료/'+safeName(label)+'.json',new Blob([JSON.stringify(rows,null,2)],{type:'application/json'})]);const cols=Array.from(new Set(rows.flatMap(Object.keys))),cell=v=>'"'+String(v==null?'':typeof v==='object'?JSON.stringify(v):v).replace(/^[=+\-@\t\r]/,'\u0027$&').replaceAll('"','""')+'"';entries.push(['표/'+safeName(label)+'.csv',new Blob(['\ufeff'+[cols.map(cell).join(','),...rows.map(r=>cols.map(k=>cell(r[k])).join(','))].join('\r\n')],{type:'text/csv;charset=utf-8'})]);}
   download(await zip(entries),'자료_'+job.coop_name+'_'+today()+'.zip');grouped.clear();entries.length=0;
   progress.replaceChildren();const summary=document.createElement('p');summary.textContent='업무자료 다운로드를 요청했습니다. '+(job.files.length?'첨부 '+job.files.length+'개는 아래 ZIP '+groups.length+'개를 모두 내려받아 주세요.':'첨부 원본은 없습니다.');progress.append(summary);
   for(const note of job.notes){const p=document.createElement('p');p.className='service-help';p.textContent=note;progress.append(p);}
   groups.forEach((batch,g)=>{
    const b=document.createElement('button');b.type='button';b.className='btn btn-primary mb-3';const label=groups.length===1?'첨부 전체를 압축파일로 받기':'첨부 ZIP '+(g+1)+' / '+groups.length+' 받기 ('+batch.length+'개)';b.textContent=label;
    b.onclick=async()=>{if(exporting)return;exporting=true;b.disabled=true;
     try{const files=[];for(let i=0;i<batch.length;i++){b.textContent='첨부 준비 중 '+(i+1)+' / '+batch.length;const f=batch[i];files.push([String(f.index+1).padStart(4,'0')+'_'+safeName(f.file.name),await fileBlob(job,f.file)]);}
      download(await zip(files),'첨부_'+job.coop_name+'_'+today()+'_'+(g+1)+'-'+groups.length+'.zip');files.length=0;b.textContent='✓ 첨부 ZIP '+(g+1)+' 다운로드 요청';
     }catch(err){b.textContent=label;message(err.message==='RETURN_CANCELLED'?'다운로드 확인을 취소했습니다.':errorText(err),'warning');}finally{exporting=false;b.disabled=false;}
    };progress.append(b);
   });
   if(job.files.length){const details=document.createElement('details'),heading=document.createElement('summary');heading.textContent='첨부를 개별 파일로 받기';details.append(heading);
    job.files.forEach((f,i)=>{const b=document.createElement('button');b.type='button';b.className='btn btn-outline-primary service-download-file';b.textContent='첨부 '+(i+1)+': '+f.name+' ('+Math.ceil(f.size/1024).toLocaleString('ko-KR')+'KB)';
     b.onclick=async()=>{if(exporting)return;exporting=true;b.disabled=true;try{download(await fileBlob(job,f),String(i+1).padStart(4,'0')+'_'+f.name);b.textContent='✓ 다운로드 요청: '+f.name;}catch(err){message(err.message==='RETURN_CANCELLED'?'다운로드 확인을 취소했습니다.':errorText(err),'warning');}finally{exporting=false;b.disabled=false;}};details.append(b);
    });progress.append(details);
   }
   message('업무자료 다운로드를 요청했습니다. 첨부 ZIP도 저장하고 반환 내역과 대조해 주세요.','success');
  }catch(err){progress.textContent=err.message==='RETURN_CANCELLED'?'자료 다운로드를 취소했습니다.':'다운로드를 완료하지 못했습니다. 일부만 받은 파일을 전체 반환 자료로 사용하지 마세요.';message(err.message==='RETURN_CANCELLED'?'PIN 확인을 취소했습니다.':errorText(err),'warning');}
  finally{exporting=false;$('exportData').disabled=false;}
 }
 window.addEventListener('pagehide',()=>{returnKey=null;returnKeyUntil=0;});
 window.addEventListener('beforeunload',e=>{if(unsaved()||window.ServiceContractCollaboration?.dirty()){e.preventDefault();e.returnValue='';}});
 async function ownershipSummary(){
  const el=$('attachmentOwnership');
  try{const s=await rpc('attachment_summary',{},null);if(!s?.assigned_legacy)return;
   el.textContent='기존 첨부 '+money(s.assigned_legacy)+'개 · '+s.coop_name+' 소유'+(s.valid_legacy<s.assigned_legacy?' · 교체·변경된 '+money(s.assigned_legacy-s.valid_legacy)+'개는 다시 확인이 필요합니다.':'');el.hidden=false;
  }catch{/* A status summary must not interrupt normal contract work. */}
 }
 async function boot(){try{
  const {data,error}=await db.auth.getUser();if(error||!data.user){location.replace('index.html?next='+encodeURIComponent(location.href));return;}
  context=await rpc('context',{},null);const {data:access,error:accessError}=await db.rpc('erp_service_access_state');if(accessError)throw accessError;
  context.download_allowed=Boolean(access?.download_allowed);$('orgName').textContent=context.party?.name||'';
  if(!context.admin&&!context.platform&&!context.representative&&!context.draft_reviewer)throw Error('SERVICE_ADMIN_REQUIRED');
  $('workspace').hidden=false;$('newContract').hidden=!context.platform||context.closed;$('exportData').hidden=!context.download_allowed;
  $('newContract').onclick=()=>{$('clientCoop').replaceChildren();for(const c of context.coops.filter(x=>x.id!==context.coop_id)){const o=document.createElement('option');o.value=c.id;o.textContent=c.name;$('clientCoop').append(o);}$('newDialog').showModal();};
  $('cancelNew').onclick=()=>$('newDialog').close();
  $('cancelReview').onclick=()=>$('reviewDialog').close();
  $('cancelReviewerLink').onclick=()=>{$('reviewerLinkDialog').close();clearReviewerLink();};$('reviewerLinkDialog').addEventListener('cancel',clearReviewerLink);$('reviewerLinkEmployee').onchange=()=>{$('reviewerLinkError').textContent='';updateReviewerLinkSelection();};$('reviewerLinkForm').onsubmit=ev=>{ev.preventDefault();if(!$('reviewerLinkForm').reportValidity())return;task(connectReviewerLink);};
  $('reviewForm').onsubmit=ev=>{ev.preventDefault();if(!$('reviewForm').reportValidity())return;const id=current.id,payload={revision:current.revision,reviewer_emp_id:$('reviewer').value,note:$('reviewRequestNote').value};task(async()=>{await rpc('review_request',payload,id);$('reviewDialog').close();await open(id);message('상대 담당자에게 검토를 요청했습니다. 상대 조합 ERP의 이용계약 목록에서 확인할 수 있습니다.','success');});};
  $('newForm').onsubmit=ev=>{ev.preventDefault();task(async()=>{if(!allowDiscard())return;const co=$('clientCoop').value,parties=await rpc('new_info',{client_coop_id:co},null);const r=await rpc('create',{client_coop_id:co,title:'협동조합 운영시스템 이용계약서',terms:defaultTerms(parties),body:defaultBody()},null);$('newDialog').close();await open(r.id,{discard:true});message('계약 초안을 만들었습니다. 실제 계약을 체결하거나 결재를 상신한 것은 아닙니다.','success');});};
  $('reloadList').onclick=()=>task(reload);$('exportData').onclick=exportData;$('cancelSign').onclick=()=>$('signDialog').close();$('clearSign').onclick=clearInk;ink();
  $('signForm').onsubmit=ev=>{ev.preventDefault();task(async()=>{if(!hasInk){message('서명을 입력해 주세요.','warning');return;}const seal=await sealPng($('sealFile').files[0]);await rpc('sign',{digest:current.digest,consent:$('signConsent').checked,signature:$('signCanvas').toDataURL('image/png'),seal});$('signDialog').close();await open(current.id);message('소속 조합 대표자의 서명·날인을 기록했습니다.','success');});};
  await reload();const id=new URLSearchParams(location.search).get('contract');if(id)await open(id);
  message(context.closed?'계약이 종료되어 자료 다운로드만 이용할 수 있습니다.':'계약을 선택해 내용을 확인해 주세요.');
  if(!context.closed&&(context.admin||context.platform))void window.VillageBilling?.init(db);
 }catch(e){message(errorText(e),'danger');}}
 // Pure helpers exposed only to regression fixtures; no authority or user token is exported.
 window.ServiceContractsUi={oneYearEnd,documentHtml,zip,print,attachmentGroups};void boot().then(()=>{if(context?.admin||context?.platform)void ownershipSummary();});
})();
