-- Version: v1.0.2
-- Change: Add ref_approval receiver/via columns for 공문 approvals.

-- Yongin Solar ERP - Schema Updates
-- 작성일: 2026-02-03
-- Date: 2026-02-03
-- 목적: ERP 알림/감사로그/권한 매트릭스 + 실물결재 문서 저장용 컬럼 추가
-- Purpose: Add ERP notifications/audit logs/role permissions + columns for physical approval documents
-- 실행 위치: Supabase SQL Editor 또는 관리자 DB 터미널
-- Execution: Supabase SQL Editor or admin DB terminal

-- ============================================================
-- 1) ERP 알림 테이블
-- 1) ERP Notifications Table
-- ============================================================
create table if not exists public.erp_notifications (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_emp_id text not null,           -- 알림 수신 대상(직원 ID)
                                       -- EN: notification recipient (employee ID)
  title text not null,                 -- 알림 제목
                                       -- EN: notification title
  message text not null,               -- 알림 내용
                                       -- EN: notification message
  type text null,                      -- 분류: approval/payroll/system 등
                                       -- EN: category (approval/payroll/system, etc.)
  link_url text null,                  -- ERP 내 이동 링크 (예: approval.html)
                                       -- EN: ERP navigation link (e.g., approval.html)
  is_read boolean not null default false,
  read_at timestamptz null,
  meta jsonb null,                     -- 부가 정보(문서 ID 등)
                                       -- EN: extra metadata (document ID, etc.)
  created_by text null                 -- 발신자(직원 ID)
                                       -- EN: sender (employee ID)
);

-- EN: ERP notification center table
comment on table public.erp_notifications is 'ERP 알림센터용 알림 테이블';
-- EN: notification recipient (ref_employees.emp_id)
comment on column public.erp_notifications.user_emp_id is '알림 수신 대상자 (ref_employees.emp_id)';
-- EN: ERP navigation link (relative path allowed)
comment on column public.erp_notifications.link_url is 'ERP 내 이동 링크 (상대 경로 가능)';
-- EN: extra metadata (document ID, etc.)
comment on column public.erp_notifications.meta is '부가 정보 (문서 ID 등)';

create index if not exists idx_erp_notifications_user on public.erp_notifications (user_emp_id);
create index if not exists idx_erp_notifications_unread on public.erp_notifications (user_emp_id, is_read);

-- ============================================================
-- 2) ERP 감사 로그 테이블
-- 2) ERP Audit Log Table
-- ============================================================
create table if not exists public.erp_audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_emp_id text null,         -- 실행자(직원 ID)
                                   -- EN: actor (employee ID)
  actor_name text null,           -- 실행자 이름(스냅샷)
                                   -- EN: actor name (snapshot)
  action text not null,           -- 동작 키 (예: approval.submit)
                                   -- EN: action key (e.g., approval.submit)
  entity_type text not null,      -- 대상 유형 (예: ref_approval)
                                   -- EN: entity type (e.g., ref_approval)
  entity_id text null,            -- 대상 ID (문서/레코드 ID)
                                   -- EN: entity ID (doc/record ID)
  summary text null,              -- 요약
                                   -- EN: summary
  detail jsonb null,              -- 변경 상세(필요 시)
                                   -- EN: change details (JSON)
  ip_address text null,           -- 선택
                                   -- EN: optional
  user_agent text null            -- 선택
                                   -- EN: optional
);

-- EN: ERP audit log for critical actions
comment on table public.erp_audit_logs is 'ERP 주요 액션 감사 로그';
-- EN: action key (approval.submit, etc.)
comment on column public.erp_audit_logs.action is '동작 키 (approval.submit 등)';
-- EN: target table/domain
comment on column public.erp_audit_logs.entity_type is '대상 테이블/도메인';
-- EN: change detail (JSON)
comment on column public.erp_audit_logs.detail is '변경 상세 (JSON)';

create index if not exists idx_erp_audit_actor on public.erp_audit_logs (actor_emp_id);
create index if not exists idx_erp_audit_entity on public.erp_audit_logs (entity_type, entity_id);

-- ============================================================
-- 3) ERP 권한 매트릭스 테이블
-- 3) ERP Role Permissions Table
-- ============================================================
create table if not exists public.erp_role_permissions (
  id bigint generated by default as identity primary key,
  scope text not null default 'role',   -- role 또는 position
                                         -- EN: role or position
  role_key text not null,               -- 역할 키 (role/position 값)
                                         -- EN: role key (role/position value)
  permission_key text not null,         -- 권한 키 (approval.view 등)
                                         -- EN: permission key (approval.view, etc.)
  is_enabled boolean not null default true,
  description text null,
  updated_at timestamptz not null default now()
);

-- EN: role/position permission matrix
comment on table public.erp_role_permissions is 'ERP 역할/직급 기반 권한 매트릭스';
-- EN: role or position mapping (ref_employees.role/position)
comment on column public.erp_role_permissions.scope is 'role 또는 position (ref_employees.role/position 매핑)';
-- EN: permission key (approval.view, accounting.edit, etc.)
comment on column public.erp_role_permissions.permission_key is '권한 키 (approval.view, accounting.edit 등)';

create unique index if not exists uk_erp_role_perm on public.erp_role_permissions (scope, role_key, permission_key);

-- ============================================================
-- 4) ref_approval 컬럼 추가 (실물결재 문서)
-- 4) Add Columns to ref_approval (Physical Approval Documents)
-- ============================================================
alter table public.ref_approval
  add column if not exists signed_doc_url text;

alter table public.ref_approval
  add column if not exists physical_approved_at timestamptz;

alter table public.ref_approval
  add column if not exists physical_approved_by text;

-- EN: signed document URL after physical approval (attachments bucket)
comment on column public.ref_approval.signed_doc_url is '실물결재 후 서명된 문서 URL (attachments 버킷)';
-- EN: physical approval completion time
comment on column public.ref_approval.physical_approved_at is '실물결재 완료 시각';
-- EN: physical approval confirmer (ref_employees.emp_id)
comment on column public.ref_approval.physical_approved_by is '실물결재 확인자 (ref_employees.emp_id)';
-- ============================================================
-- 9) 공문 결재용 필드 (수신/경유)
-- 9) Fields for official notices (receiver/via)
-- ============================================================
ALTER TABLE public.ref_approval
  ADD COLUMN IF NOT EXISTS receiver text;

ALTER TABLE public.ref_approval
  ADD COLUMN IF NOT EXISTS via text;
